"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _stat_card_1 from './stat-card-1.bones.json'
import _stat_card_2 from './stat-card-2.bones.json'
import _stat_card_3 from './stat-card-3.bones.json'
import _stat_card_4 from './stat-card-4.bones.json'
import _cash_flow_chart from './cash-flow-chart.bones.json'
import _recent_transactions from './recent-transactions.bones.json'

registerBones({
  "stat-card-1": _stat_card_1,
  "stat-card-2": _stat_card_2,
  "stat-card-3": _stat_card_3,
  "stat-card-4": _stat_card_4,
  "cash-flow-chart": _cash_flow_chart,
  "recent-transactions": _recent_transactions,
})
